### PR TITLE
bugfix/emoji-delete-bug-issue-61

### PR DESCRIPTION
**Pull request by Substancia**
Converted string of emojis into array of emojis.

This is a functionality fix, unaffected by upcoming UI changes. Can delay PR merge till after the UI change, will not cause merge conflicts either.

### CODE REVIEW

**Comment by aditya-singh9** [comment]
It also has some merge conflicts, please resolve them too

**Comment by aditya-singh9** [comment]
Please look into the [preview](https://kekfinder-pqqt82ht7-aditya-singh9.vercel.app/)

**Comment by aditya-singh9** [comment]
@Substancia when you are done, please leave a comment.
Thanks

**Comment by Substancia** [comment]
@Rudresh-pandey can you please confirm on the latest commit whether this problem persists? I can't reproduce this.

@aditya-singh9 The footer seems to be not appropriately coded, and has an individual library used just for the footer into which I'll have to look into first. I think we can take it up under the [footer issue](https://github.com/aditya-singh9/kekfinder/issues/34) or an entirely new issue maybe?

New commits have been made merging the UI changes, resolving merge conflicts, and reapplying changes. Please take a look.

**Comment by Rudresh-pandey** [comment]
Sorry it was my mistake , i added the website footer code in mobile view

**Comment by Substancia** [comment]
Can we shift the footer conversation to the [footer issue](https://github.com/aditya-singh9/kekfinder/issues/34)? That way we can decouple the problems and close (or discuss) only this bug here.

**Comment by Substancia** [comment]
My bad on the footer issue, somehow a position attribute got added accidentally while rebasing my branch. I've put it back to how it was.

Screenshot 2022-10-05 at 18 51 52
Screenshot 2022-10-05 at 18 52 04
Screenshot 2022-10-05 at 18 52 10

Looks like originally the footer won't stick to the bottom when the emojis list is empty. Do we want it that way?

**Comment by Rudresh-pandey** [comment]
@Substancia  , @aditya-singh9 , @ArunBohra12 
plz try to run this #72 in your local server and check whether it's working or not

**Comment by Substancia** [comment]
@Rudresh-pandey the desktop/mobile view switching is working on mine, but the [footer isn't sticking when width < 1400px](https://github.com/aditya-singh9/kekfinder/issues/34#issuecomment-1268479126).

**Comment by aditya-singh9** [comment]
Everythings working iguess

[Preview](https://kekfinder-q72869wgr-aditya-singh9.vercel.app/)

**Comment by Substancia** [comment]
@Rudresh-pandey @aditya-singh9 the footer in big screen is on right side, is that intentional?

Screenshot 2022-10-05 at 19 34 39

**Comment by Rudresh-pandey** [comment]
> My bad on the footer issue, somehow a position attribute got added accidentally while rebasing my branch. I've put it back to how it was.
> 
> Screenshot 2022-10-05 at 18 51 52
> 
> Screenshot 2022-10-05 at 18 52 04
> 
> Screenshot 2022-10-05 at 18 52 10
> 
> Looks like originally the footer won't stick to the bottom when the emojis list is empty. Do we want it that way?

**yes we want the footer at the bottom when list is empty** in mobile view and tablet view

**Comment by aditya-singh9** [comment]
I guess we should address these somewhere else.

**Pull request merged**
