### PR TITLE
newUI

### PR DESCRIPTION
**Pull request by Rudresh-pandey**
### **newUI for desktop view and mobile view**

_see issue #46 for more_

:)

### CODE REVIEW

**Comment by aditya-singh9** [comment]
Can you please address this issue

I used desktop view in mobile phone and this showed up

**Comment by Rudresh-pandey** [comment]
Because i made this responsive only for desktop and mobile. I think i have to make more media queries .

**Comment by Rudresh-pandey** [comment]
How can we code for desktop view in mobile . @aditya-singh9 , @Substancia

**Comment by Rudresh-pandey** [comment]
https://user-images.githubusercontent.com/96531798/193963955-98aa2594-ffd5-47f5-a18b-24dcc4f28202.mp4

**Comment by Rudresh-pandey** [comment]
need to push again the changes

**Pull request closed without merging**
