### PR TITLE
#37 Updated UI 

### PR DESCRIPTION
**Pull request by Rudresh-pandey**
### **Updated UI :** 

1 .  Updated items shadow colour
2 .  Updated search - bar border colour on focus and changed the font width
3 .  Updated Scroll - bar colour

### **Preview :**

    **_Light Theme_**
image

    **_Drak Theme_**
image

### CODE REVIEW

**Comment by aditya-singh9** [comment]
It has merge conflicts, please resolve then commit.

**Comment by Rudresh-pandey** [comment]
Try kiye the resolve karne ka , lekin phir vercel pe error aa raha tha

**Comment by aditya-singh9** [comment]
What error is given by vercel?

And i cannot merge it with merge conflicts

**Comment by Rudresh-pandey** [comment]
Trying to resolve it :)

**Pull request merged**
